* Diana text processing adventures

* TODO/DONE

** porting/cleaning old diana nltk code: 

https://github.com/nltk/nltk/wiki/Porting-your-code-to-NLTK-3.0

port notes: always use textclean:

: from textclean.textclean import textclean
: crash_raw = textclean.clean(crash_raw)

or better:

: def removeNonAscii(s): return "".join(i for i in s if ord(i)<128)

re-pickling tagged and nodes/label(), lack of nltk.NgramModel!

paths: /root/diana/chapters/3_glass-crash/

** break up functionality/more understanding of what can be done

* TUE 6 JAN 2015

- test6.py cleaned up and renamed as customgrammars.py
- slimmedrel (named entities), genetic2, afterbrendan, execute_threaded, listallxxx
- discard in discard.py
- cleaned up isbrand


ported DONE:
delaynoun.py
test7.py
old.py NADA
weight-test.py - bestrawscore now!
test.py - still double clean text first!
naivesumm.py
summarize.py
executing.py
concord.py
weight-test2.py
ballardmatcher.py
genetic.py
test3.py
test2.py - redone pickle!
relrandom.py - redo pickle!
ngrammatch.py - replaced with markov

* FRI 2 JAN 2015

git!

*** TODO:

// all from diana/chapters
- port to new NLTK/Python
- clean up with pickling and break down into more functional segments
- path names!

* Texts

** summarize.py on crash.txt

Cruising alone on the motorway under the yellow glare of the sodium
lights, I thought of myself at the controls of these impacting
vehicles. Two months before my accident, during a journey to Paris, I
had become so excited by the conjunction of an air hostess's fawn
gaberdine skirt on the escalator in front of me and the distant
fuselages of the aircraft, each inclined like a silver penis towards
her natal cleft, that I had involuntarily touched her left buttock.

** relrandom as very interesting

I tried to visualize the childhood that had created this beautiful
young woman, the perfect forgery of an Henri Paul.
